### ISSUE TITLE
rails 4?

### ISSUE THREAD

**Issue by hopewise** [livebg/smailer#16]
Does it support rails 4? Or there is work to do?

**Comment by mitio** [comment]
I have not tested it in Rails 4 yet, but I think @noijd has used it in Rails 4.1.x ([see this PR for example](https://github.com/livebg/smailer/pull/8)).

Even if it does not work out of the box, I believe support can be added easily. The lib uses a few ActiveRecord query methods which are also supported in Rails 4 as well as the ActionMailer interface, which has remained the same I think.

@hopewise If you're up to try it out and report any issues, it would be great.

**Comment by hopewise** [comment]
Thanks for fast reply, I am trying to make a decision, between maktoub and
your gem

Does it support delayed job? Or to use a worker?

**Comment by mitio** [comment]
Sending is done via a task you have to run somehow. You can run it in a job
queue, or in a rake task via a periodic cronjob. I'm using the second
approach in my projects, to be able to control the sending rate of emails
per hour, since our queues are quite large (tens of thousands of emails per
day).

**Comment by hopewise** [comment]
Can I use a normal view as the content of sender email?

Is there an example if using periodic cronjob?

Thank you!

**Comment by mitio** [comment]
@hopewise There is no built-in support for rendering a view as an email. The library expects you to have created the content of the email (HTML and plain text) beforehand. There is some [documentation and examples regarding that in the readme](https://github.com/livebg/smailer#usage-and-documentation).

The readme also contains [an example of the aforementioned periodic (cron) job](https://github.com/livebg/smailer#sending-mails).

I'm closing this issue for now, but feel free to reopen it, if you plan to try the gem on Rails 4 and find the time to report back what the result was.
