### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by mitio** [livebg/smailer#2]
Better later than never. This project needs tests badly.

**Comment by noijd** [comment]
How about using RSpec?

**Comment by noijd** [comment]
I have been reviewing the code, and I would like to start adding some easy tests. So, would you mind if I choose RSpec for that matter?

**Comment by mitio** [comment]
RSpec is cool. It's a development dependency, so I don't mind adding one, esp. if you are really going to add some tests. Which would be awesome :heart:

**Comment by noijd** [comment]
Ok, then I am going to begin with some models.
