### ISSUE TITLE
Rails 5 attr_accessible issue

### ISSUE THREAD

**Issue by nikhilm492** [livebg/smailer#22]
We are using rails version 5.0.0

Smailer usage is giving us an error because attr_accessible method in models has been removed in Rails 5. Could you remove them from the models, please?

**Comment by mitio** [comment]
Thanks for reporting this.

I'll try to push an updated version in the coming few days.

**Comment by mitio** [comment]
This should be fixed in version 0.8.3. Thanks for the patience!
